- hosts: localhost
  become: true
  pre_tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes
  tasks:
  - include: tasks/zsh.yml
  - include: tasks/node.yml
  - include: tasks/git.yml
