- hosts: localhost
  become: true
  pre_tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes
  tasks:
  - name: Install zsh
    ansible.builtin.apt:
      name: zsh
    tags:
    - zsh
  - name: Configure zsh as shell
    shell: chsh -s `which zsh`
    tags:
    - zsh
  - name: Install Oh My Zsh
    shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -s
    tags:
    - zsh
  - name: Install node and npm
    ansible.builtin.apt:
      name: ['nodejs', 'npm']
    tags:
    - node
  - name: Install N
    community.general.npm:
      name: n
      global: true
      state: latest
    tags:
    - node
  - name: Install node version 20
    shell: n 20
    tags:
    - node
