- name: Install neovim dependencies
  ansible.builtin.apt:
    name: [ninja-build, gettext, cmake, unzip, curl, build-essential]
    state: present
  tags:
    - build
    - neovim
- name: Clone neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    clone: true
    version: stable
  tags:
    - neovim
- name: Build binaries
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  tags:
    - neovim
- name: Install neovim\
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
    target: install
  tags:
    - neovim
