- name: Check if .ssh directory exists
  ansible.builtin.file:
    path: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Install private ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - ssh

- name: Install public ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0600
  tags:
    - ssh
